// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadMetadataTemplate() {
  return window['go']['main']['App']['DownloadMetadataTemplate']();
}

export function ExportAnalysisReport(arg1, arg2) {
  return window['go']['main']['App']['ExportAnalysisReport'](arg1, arg2);
}

export function FetchRealReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchRealReport'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetESInfo() {
  return window['go']['main']['App']['GetESInfo']();
}

export function GetMetadata() {
  return window['go']['main']['App']['GetMetadata']();
}

export function RunAnalysis(arg1) {
  return window['go']['main']['App']['RunAnalysis'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveMetadata(arg1) {
  return window['go']['main']['App']['SaveMetadata'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function TestDBConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['TestDBConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function TestESConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestESConnection'](arg1, arg2, arg3, arg4);
}

export function UploadMetadata() {
  return window['go']['main']['App']['UploadMetadata']();
}
