// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function DownloadMetadataTemplate():Promise<string>;

export function ExportAnalysisReport(arg1:string,arg2:string):Promise<string>;

export function FetchRealReport(arg1:string,arg2:string,arg3:string):Promise<Array<main.AnalysisResult>>;

export function GetConfig():Promise<config.Config>;

export function GetESInfo():Promise<string>;

export function GetMetadata():Promise<Array<main.BehaviorMetadata>>;

export function RunAnalysis(arg1:Array<main.BehaviorMetadata>):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function SaveMetadata(arg1:Array<main.BehaviorMetadata>):Promise<string>;

export function SelectFile():Promise<string>;

export function TestDBConnection(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<string>;

export function TestESConnection(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function UploadMetadata():Promise<string>;
